In [16]:
import pandas as pd
import numpy as np
import scanpy as sc
# import seaborn as sns

In [2]:
f = '/home/qlyu/mydata/data/v1_astro/t2p1/spout/eRegulons_extended.tsv'
df_reg = pd.read_csv(f, sep='\t')
df_reg

,Region,Gene,importance_R2G,rho_R2G,importance_x_rho,importance_x_abs_rho,TF,is_extended,eRegulon_name,Gene_signature_name,Region_signature_name,importance_TF2G,regulation,rho_TF2G,triplet_rank
0,chr10:106509496-106509997,Ppfia2,0.046498,0.402633,0.018721,0.018721,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.062220,1,0.169628,8231
1,chr10:5920901-5921402,Rgs17,0.052824,0.286791,0.015149,0.015149,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.077808,1,0.076129,8243
2,chr7:66477452-66477953,Adamts17,0.019693,0.238252,0.004692,0.004692,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.414283,1,0.107210,8053
3,chr2:142882918-142883419,Kif16b,0.038594,0.161458,0.006231,0.006231,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.116308,1,0.054228,8767
4,chr15:94981752-94982253,Nell2,0.102605,0.347766,0.035683,0.035683,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.113302,1,0.157144,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8925,chr14:60385045-60385546,Atp8a2,0.001961,-0.408837,-0.000802,0.000802,Sox9,True,Sox9_extended_-/-,Sox9_extended_-/-_(240g),Sox9_extended_-/-_(334r),0.808974,-1,-0.220428,8773
8926,chr18:24862866-24863367,Fhod3,0.021229,-0.356405,-0.007566,0.007566,Sox9,True,Sox9_extended_-/-,Sox9_extended_-/-_(240g),Sox9_extended_-/-_(334r),0.710168,-1,-0.231326,8673
8927,chr1:163574556-163575057,Kifap3,0.148091,-0.199352,-0.029522,0.029522,Sox9,True,Sox9_extended_-/-,Sox9_extended_-/-_(240g),Sox9_extended_-/-_(334r),0.693625,-1,-0.116417,608
8928,chr5:14539225-14539726,Pclo,0.134226,-0.392825,-0.052727,0.052727,Sox9,True,Sox9_extended_-/-,Sox9_extended_-/-_(240g),Sox9_extended_-/-_(334r),0.545483,-1,-0.245657,1168
8929,chr7:81418025-81418526,Tm6sf1,0.025713,-0.140714,-0.003618,0.003618,Sox9,True,Sox9_extended_-/-,Sox9_extended_-/-_(240g),Sox9_extended_-/-_(334r),0.655930,-1,-0.066879,7026

In [3]:
df_reg['sign'] = df_reg['Gene_signature_name'].apply(lambda x: x.split('(')[0][-4:-1].replace('/',''))
df_reg = df_reg[df_reg['sign'].isin(['++', '-+'])]
df_reg['TF'].unique()

array(['Ar', 'Dbx2', 'Egr1', 'Hes5', 'Klf10', 'Mef2c', 'Nfia', 'Nfyc',
       'Nr2e1', 'Pou2f1', 'Pou3f2', 'Prrx1', 'Sox6', 'Sox9', 'Zfp148',
       'Zfp704', 'Cux1', 'Cux2', 'Lcorl', 'Pou6f2', 'Satb2'], dtype=object)

In [4]:
df_reg

,Region,Gene,importance_R2G,rho_R2G,importance_x_rho,importance_x_abs_rho,TF,is_extended,eRegulon_name,Gene_signature_name,Region_signature_name,importance_TF2G,regulation,rho_TF2G,triplet_rank,sign
0,chr10:106509496-106509997,Ppfia2,0.046498,0.402633,0.018721,0.018721,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.062220,1,0.169628,8231,++
1,chr10:5920901-5921402,Rgs17,0.052824,0.286791,0.015149,0.015149,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.077808,1,0.076129,8243,++
2,chr7:66477452-66477953,Adamts17,0.019693,0.238252,0.004692,0.004692,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.414283,1,0.107210,8053,++
3,chr2:142882918-142883419,Kif16b,0.038594,0.161458,0.006231,0.006231,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.116308,1,0.054228,8767,++
4,chr15:94981752-94982253,Nell2,0.102605,0.347766,0.035683,0.035683,Ar,True,Ar_extended_+/+,Ar_extended_+/+_(17g),Ar_extended_+/+_(17r),0.113302,1,0.157144,2004,++
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5421,chr1:182448158-182448659,Capn2,0.040880,0.162940,0.006661,0.006661,Satb2,True,Satb2_extended_-/+,Satb2_extended_-/+_(104g),Satb2_extended_-/+_(151r),0.825970,-1,-0.189191,5683,-+
5422,chr5:9541104-9541605,Grm3,0.081643,0.287862,0.023502,0.023502,Satb2,True,Satb2_extended_-/+,Satb2_extended_-/+_(104g),Satb2_extended_-/+_(151r),2.361505,-1,-0.324911,1160,-+
5423,chr16:33832797-33833298,Itgb5,0.019068,0.317532,0.006055,0.006055,Satb2,True,Satb2_extended_-/+,Satb2_extended_-/+_(104g),Satb2_extended_-/+_(151r),0.755655,-1,-0.279096,2914,-+
5424,chr11:112811668-112812169,Sox9,0.054879,0.368038,0.020198,0.020198,Satb2,True,Satb2_extended_-/+,Satb2_extended_-/+_(104g),Satb2_extended_-/+_(151r),1.203008,-1,-0.272652,2231,-+
5425,chr2:179877349-179877850,Rps21,0.068699,0.052828,0.003629,0.003629,Satb2,True,Satb2_extended_-/+,Satb2_extended_-/+_(104g),Satb2_extended_-/+_(151r),2.904714,-1,-0.139047,1594,-+

In [5]:
df_reg_sum = df_reg.groupby(['TF', 'sign']).first()[['Gene_signature_name', 'Region_signature_name']]
df_reg_sum['num_genes'] = df_reg_sum['Gene_signature_name'].apply(lambda x: x.split('(')[1])
df_reg_sum['num_regions'] = df_reg_sum['Region_signature_name'].apply(lambda x: x.split('(')[1])
df_reg_sum = df_reg_sum[['num_genes', 'num_regions']]
df_reg_sum.head(60)

            num_genes num_regions
TF     sign
Ar     ++        17g)        17r)
Cux1   -+        13g)        19r)
Cux2   -+        17g)        34r)
Dbx2   ++       163g)       214r)
Egr1   ++        17g)        16r)
Hes5   ++        14g)        12r)
Klf10  ++        18g)        17r)
Lcorl  -+        11g)        13r)
Mef2c  ++        57g)        62r)
Nfia   ++       517g)      1043r)
Nfyc   ++        33g)        38r)
Nr2e1  ++       350g)       539r)
Pou2f1 ++        46g)        59r)
       -+        33g)        32r)
Pou3f2 ++        12g)        13r)
Pou6f2 -+        11g)        21r)
Prrx1  ++       191g)       379r)
Satb2  -+       104g)       151r)
Sox6   ++        84g)        91r)
Sox9   ++       301g)       497r)
Zfp148 ++        12g)        12r)
Zfp704 ++        12g)        12r)

In [6]:
f = '/home/qlyu/mydata/data/v1_astro/t2p1/spout/tf_to_gene_adj.tsv'
df_raw = pd.read_csv(f, sep='\t')
df = df_raw[df_raw['TF']=='Rfx4']
df

           TF     target  importance  regulation       rho
850921   Rfx4      Wdr78    0.683830          -1 -0.074873
850922   Rfx4       Scd1    0.138878           1  0.070475
850923   Rfx4       Tcap    0.022379           0 -0.026468
850924   Rfx4    Gm12841    0.012491           0 -0.022492
850925   Rfx4     Atp5g1    0.080932           0 -0.003300
...       ...        ...         ...         ...       ...
861001   Rfx4  Bloc1s6os    0.403807           1  0.060831
861002   Rfx4     Paxbp1    0.298478           0  0.019044
861003   Rfx4    Dennd1b    0.309615          -1 -0.054802
861004   Rfx4       Twf2    1.038107          -1 -0.094464
1274028  Rfx4       Rfx4   14.962339           1  1.000000

[10085 rows x 5 columns]

In [7]:
df['regulation'].value_counts()

-1    3946
 1    3086
 0    3053
Name: regulation, dtype: int64

In [8]:
df['rhoa'] = np.abs(df['rho'])
df['importance_rank_pct'] = df['importance'].rank(pct=True, ascending=False)
df['importance_rank'] = df['importance'].rank(ascending=False)
df.groupby('regulation').mean()

/tmp/ipykernel_3321743/2507916231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rhoa'] = np.abs(df['rho'])
/tmp/ipykernel_3321743/2507916231.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['importance_rank_pct'] = df['importance'].rank(pct=True, ascending=False)
/tmp/ipykernel_3321743/2507916231.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['importance_rank'] = df['importance'].rank(ascending=False)
/tmp/ipykernel_3321743/2507916231.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('regulation').mean()

,importance,rho,rhoa,importance_rank_pct,importance_rank
regulation,,,,,
-1,0.942386,-0.119830,0.119830,0.458396,4622.920679
0,0.287647,-0.000343,0.013646,0.694883,7007.897478
1,1.242810,0.139551,0.139551,0.360561,3636.260207

In [9]:
assert 'Mertk' in df['target'].unique()
df[df['target']=='Mertk']

,TF,target,importance,regulation,rho,rhoa,importance_rank_pct,importance_rank
859624,Rfx4,Mertk,7.55098,1,0.665074,0.665074,0.006842,69.0

In [10]:
df.sort_values('importance_rank')

,TF,target,importance,regulation,rho,rhoa,importance_rank_pct,importance_rank
1274028,Rfx4,Rfx4,1.496234e+01,1,1.000000,1.000000,0.000099,1.0
860352,Rfx4,Npas3,1.496233e+01,1,0.663597,0.663597,0.000198,2.0
859888,Rfx4,Qk,1.452436e+01,1,0.606366,0.606366,0.000297,3.0
859845,Rfx4,Ptprz1,1.402828e+01,1,0.676867,0.676867,0.000397,4.0
860059,Rfx4,Zbtb20,1.388092e+01,1,0.660149,0.660149,0.000496,5.0
...,...,...,...,...,...,...,...,...
860887,Rfx4,Phlda1,1.339995e-16,0,0.010923,0.010923,0.999603,10081.0
860967,Rfx4,Morn2,1.324729e-16,0,-0.013685,0.013685,0.999703,10082.0
860978,Rfx4,Slc33a1,1.304858e-16,0,0.023576,0.023576,0.999802,10083.0
860485,Rfx4,Nog,6.708835e-17,0,0.000916,0.000916,0.999901,10084.0
860849,Rfx4,Gm48226,5.223444e-17,0,0.006892,0.006892,1.000000,10085.0

In [11]:
dft = df_raw[df_raw['target']=='Mertk']
dft

             TF target  importance  regulation       rho
6571     Acaa1a  Mertk    0.002304           0  0.026018
10463        Ar  Mertk    0.124882          -1 -0.178102
32815       Arx  Mertk    0.009629           1  0.217826
44845      Atf2  Mertk    0.219652          -1 -0.196187
54127      Atf6  Mertk    0.060753          -1 -0.221831
...         ...    ...         ...         ...       ...
1230952  Zfp704  Mertk    0.448964          -1 -0.280004
1235971  Zfp711  Mertk    0.023768          -1 -0.163171
1246956  Zfp786  Mertk    0.007449           0 -0.027260
1253333  Zfp941  Mertk    0.001856          -1 -0.042136
1255848     Zfx  Mertk    0.002653           0 -0.000723

[108 rows x 5 columns]

In [12]:
dft['regulation'].value_counts()

 1    51
-1    42
 0    15
Name: regulation, dtype: int64

In [13]:
dft.sort_values('importance', ascending=False).head(20)

             TF target  importance  regulation       rho
969789     Sox6  Mertk   22.057346           1  0.770120
606353     Nfia  Mertk   12.060209           1  0.634558
518954    Mef2c  Mertk   10.648191          -1 -0.721814
788972   Prdm16  Mertk    8.679278           1  0.670948
859624     Rfx4  Mertk    7.550980           1  0.665074
1134823    Zeb1  Mertk    5.410750           1  0.467014
179974     Dbx2  Mertk    4.182561           1  0.617155
888815    Satb2  Mertk    4.142290          -1 -0.530645
90060    Bcl11a  Mertk    3.306795          -1 -0.493170
294503    Foxo1  Mertk    3.270311           1  0.595131
1031195    Tcf4  Mertk    2.988583           1  0.404279
332385     Hes5  Mertk    2.639081           1  0.490625
982838     Sox9  Mertk    2.281713           1  0.460142
691253    Nr2e1  Mertk    1.686883           1  0.456134
819903      Rb1  Mertk    1.471887           1  0.349341
528395    Meis1  Mertk    1.073645           1  0.409066
798925    Prrx1  Mertk    0.777303           1  0.538569
269380     Etv4  Mertk    0.717400           1  0.413425
720870     Pax6  Mertk    0.621343           1  0.406236
1008474  Srebf1  Mertk    0.574972           1  0.365652

# region to gene

In [57]:
f = '/home/qlyu/mydata/data/v1_astro/t2/spout/region_to_gene_adj.tsv'
df2_raw = pd.read_csv(f, sep='\t')
df2_raw['importance_x_abs_rho_rank'] = df2_raw['importance_x_abs_rho'].rank(pct=True, ascending=False) 
print(df2_raw.shape)
df2 = df2_raw[df2_raw['target']=='Mertk'].sort_values('importance_x_abs_rho', ascending=False)
print(df2.shape)
gspec_regions = df2['region'].values
df2
# df

(680504, 8)
(47, 8)

,target,region,importance,rho,importance_x_rho,importance_x_abs_rho,Distance,importance_x_abs_rho_rank
338178,Mertk,chr2:128709104-128709605,1.184319e-01,0.746525,8.841242e-02,8.841242e-02,[-64540],0.000075
338146,Mertk,chr2:128497800-128498301,9.424160e-02,-0.896956,-8.453054e-02,8.453054e-02,[42826],0.000084
338179,Mertk,chr2:128704410-128704911,8.572007e-02,0.800078,6.858272e-02,6.858272e-02,[-59846],0.000199
338180,Mertk,chr2:128698559-128699060,1.129459e-01,0.573247,6.474588e-02,6.474588e-02,[-53996],0.000254
338173,Mertk,chr2:128745803-128746304,9.929474e-02,0.602391,5.981430e-02,5.981430e-02,[-101240],0.000350
338181,Mertk,chr2:128698013-128698514,7.017670e-02,0.768135,5.390518e-02,5.390518e-02,[-53450],0.000534
338168,Mertk,chr2:128786705-128787206,5.544115e-02,0.887918,4.922718e-02,4.922718e-02,[-142142],0.000762
338182,Mertk,chr2:128687421-128687922,6.059751e-02,-0.564160,-3.418668e-02,3.418668e-02,[-42858],0.002649
338174,Mertk,chr2:128738704-128739205,5.963683e-02,0.566037,3.375664e-02,3.375664e-02,[-94140],0.002768
338184,Mertk,chr2:128686977-128687478,4.524357e-02,0.738566,3.341536e-02,3.341536e-02,[-42414],0.002860
338169,Mertk,chr2:128758624-128759125,3.581964e-02,0.879016,3.148603e-02,3.148603e-02,[-114060],0.003412
338159,Mertk,chr2:128444598-128445099,2.597790e-02,0.849919,2.207912e-02,2.207912e-02,[96028],0.007772
338175,Mertk,chr2:128717686-128718187,2.444875e-02,0.856874,2.094949e-02,2.094949e-02,[-73122],0.008675
338148,Mertk,chr2:128566706-128567207,1.430078e-02,0.892188,1.275898e-02,1.275898e-02,[0],0.021099
338190,Mertk,chr2:128395820-128396321,1.654359e-02,0.764221,1.264296e-02,1.264296e-02,[144806],0.021402
338155,Mertk,chr2:128465130-128465631,1.371785e-02,-0.781564,-1.072138e-02,1.072138e-02,[75496],0.027571
338162,Mertk,chr2:128414519-128415020,1.149126e-02,-0.880915,-1.012283e-02,1.012283e-02,[126106],0.029876
338177,Mertk,chr2:128713420-128713921,1.351887e-02,0.569186,7.694756e-03,7.694756e-03,[-68856],0.042846
338149,Mertk,chr2:128498481-128498982,9.936025e-03,-0.448883,-4.460116e-03,4.460116e-03,[42144],0.079525
338152,Mertk,chr2:128498215-128498716,9.072077e-03,-0.472458,-4.286173e-03,4.286173e-03,[42410],0.082793
338145,Mertk,chr2:128468965-128469466,7.774823e-03,-0.546258,-4.247059e-03,4.247059e-03,[71660],0.083563
338187,Mertk,chr2:128412012-128412513,4.280716e-03,-0.495342,-2.120420e-03,2.120420e-03,[128614],0.160045
338166,Mertk,chr2:128678605-128679106,3.525711e-03,0.426438,1.503496e-03,1.503496e-03,[-34042],0.210917
338154,Mertk,chr2:128458041-128458542,2.726128e-03,-0.228362,-6.225446e-04,6.225446e-04,[82584],0.367145
338151,Mertk,chr2:128572782-128573283,1.787902e-03,-0.321811,-5.753666e-04,5.753666e-04,[0],0.382158
338171,Mertk,chr2:128746788-128747289,7.487170e-04,0.296976,2.223509e-04,2.223509e-04,[-102224],0.551755
338183,Mertk,chr2:128687163-128687664,3.322620e-04,-0.338391,-1.124346e-04,1.124346e-04,[-42600],0.654718
338167,Mertk,chr2:128674526-128675027,3.386606e-04,0.264365,8.952999e-05,8.952999e-05,[-29962],0.684836
338165,Mertk,chr2:128603050-128603551,2.529010e-04,0.171162,4.328699e-05,4.328699e-05,[0],0.766138
338170,Mertk,chr2:128758293-128758794,1.737546e-04,0.187761,3.262432e-05,3.262432e-05,[-113730],0.792279
338186,Mertk,chr2:128678829-128679330,1.409795e-04,-0.174713,-2.463098e-05,2.463098e-05,[-34266],0.815521
338161,Mertk,chr2:128429092-128429593,3.070721e-04,0.065625,2.015159e-05,2.015159e-05,[111534],0.830701
338185,Mertk,chr2:128686736-128687237,8.281312e-05,0.151475,1.254415e-05,1.254415e-05,[-42172],0.861755
338189,Mertk,chr2:128662064-128662565,2.077763e-04,0.056710,1.178292e-05,1.178292e-05,[-17500],0.865466
338160,Mertk,chr2:128432681-128433182,6.211399e-05,-0.181386,-1.126663e-05,1.126663e-05,[107944],0.868013
338157,Mertk,chr2:128457761-128458262,6.301598e-05,0.078882,4.970806e-06,4.970806e-06,[82864],0.906720
338176,Mertk,chr2:128717408-128717909,1.323604e-04,-0.021936,-2.903401e-06,2.903401e-06,[-72844],0.925133
338163,Mertk,chr2:128412306-128412807,4.990710e-05,0.034963,1.744910e-06,1.744910e-06,[128320],0.938580
338150,Mertk,chr2:128467391-128467892,3.891887e-05,-0.042971,-1.672370e-06,1.672370e-06,[73234],0.939554
338147,Mertk,chr2:128497940-128498441,2.120373e-04,0.007118,1.509236e-06,1.509236e-06,[42686],0.941864
338156,Mertk,chr2:128573122-128573623,1.036775e-04,-0.010986,-1.138966e-06,1.138966e-06,[0],0.947699
338172,Mertk,chr2:128746221-128746722,2.707757e-05,0.040824,1.105404e-06,1.105404e-06,[-101658],0.948275
338191,Mertk,chr2:128537335-128537836,3.128003e-05,0.017860,5.586666e-07,5.586666e-07,[3290],0.959093
338164,Mertk,chr2:128465517-128466018,3.784246e-05,0.014078,5.327630e-07,5.327630e-07,[75108],0.959732
338153,Mertk,chr2:128467013-128467514,7.894096e-07,-0.023889,-1.885838e-08,1.885838e-08,[73612],0.981955
338158,Mertk,chr2:128457059-128457560,3.992519e-06,-0.003892,-1.553748e-08,1.553748e-08,[83566],0.982468
338188,Mertk,chr2:128676094-128676595,1.696258e-08,-0.014572,-2.471747e-10,2.471747e-10,[-31530],0.987977

# cistrome

In [43]:
f = '/home/qlyu/mydata/data/v1_astro/t2p1/spout/cistromes_extended.h5ad'
adata_cis = sc.read(f)
adata_cis

/home/qlyu/miniforge3/envs/scenicplus2/lib/python3.11/site-packages/anndata/__init__.py:51: FutureWarning: `anndata.read` is deprecated, use `anndata.read_h5ad` instead. `ad.read` will be removed in mid 2024.
  warnings.warn(

AnnData object with n_obs × n_vars = 36199 × 505
    var: 'motifs', 'is_extended'

In [44]:
adata_cis.var.loc['Rfx4']

motifs         metacluster_136.3
is_extended                 True
Name: Rfx4, dtype: object

In [45]:
instances = np.array(adata_cis[:,['Rfx3', 'Rfx4',]].X.todense()) # .obs

In [46]:
np.all(instances[:,0] == instances[:,1])

True

In [47]:
instances[:,0].sum()

46

In [48]:
instances[:,1].sum()

46

In [49]:
adata_cis.obs[instances[:,1]].sort_index()

Empty DataFrame
Columns: []
Index: [chr10:20018278-20018779, chr11:111777609-111778110, chr11:4069602-4070103, chr11:70029451-70029952, chr11:96875470-96875971, chr12:102107735-102108236, chr12:111064128-111064629, chr12:119464093-119464594, chr12:51024347-51024848, chr12:71606074-71606575, chr12:99457766-99458267, chr13:113324160-113324661, chr13:19701336-19701837, chr13:19921309-19921810, chr13:55483542-55484043, chr14:60992200-60992701, chr15:17427639-17428140, chr16:12800207-12800708, chr16:33055672-33056173, chr17:70826146-70826647, chr17:79887903-79888404, chr17:8368577-8369078, chr18:60924710-60925211, chr19:47484038-47484539, chr1:46912332-46912833, chr2:167201396-167201897, chr2:25549318-25549819, chr2:4137377-4137878, chr3:107430032-107430533, chr3:108536403-108536904, chr3:127265661-127266162, chr4:155840335-155840836, chr4:76405698-76406199, chr5:35245372-35245873, chr5:42417573-42418074, chr6:40015956-40016457, chr7:18922784-18923285, chr8:113755332-113755833, chr8:120329263-120329764, chr8:123234758-123235259, chr8:36288233-36288734, chr8:84985911-84986412, chr8:8574980-8575481, chr9:59588765-59589266, chrX:11620901-11621402, chrX:74836705-74837206]

In [50]:
sel_regions = adata_cis.obs.index.values
sel_regions

array(['chr13:31878716-31879217', 'chr4:62543736-62544237',
       'chr14:63383515-63384016', ..., 'chr7:34196164-34196665',
       'chr1:157232309-157232810', 'chr14:70834668-70835169'],
      dtype=object)

In [52]:
sel_regions.shape

(36199,)

In [61]:
sel_regions_gspec = np.intersect1d(gspec_regions, sel_regions)

In [62]:
df2.set_index('region').loc[sel_regions_gspec]

,target,importance,rho,importance_x_rho,importance_x_abs_rho,Distance,importance_x_abs_rho_rank
region,,,,,,,
chr2:128444598-128445099,Mertk,0.025978,0.849919,0.022079,0.022079,[96028],0.007772
chr2:128566706-128567207,Mertk,0.014301,0.892188,0.012759,0.012759,[0],0.021099
chr2:128698559-128699060,Mertk,0.112946,0.573247,0.064746,0.064746,[-53996],0.000254
chr2:128709104-128709605,Mertk,0.118432,0.746525,0.088412,0.088412,[-64540],0.000075
chr2:128713420-128713921,Mertk,0.013519,0.569186,0.007695,0.007695,[-68856],0.042846
chr2:128717686-128718187,Mertk,0.024449,0.856874,0.020949,0.020949,[-73122],0.008675
chr2:128738704-128739205,Mertk,0.059637,0.566037,0.033757,0.033757,[-94140],0.002768
chr2:128745803-128746304,Mertk,0.099295,0.602391,0.059814,0.059814,[-101240],0.000350
chr2:128758293-128758794,Mertk,0.000174,0.187761,0.000033,0.000033,[-113730],0.792279
chr2:128758624-128759125,Mertk,0.035820,0.879016,0.031486,0.031486,[-114060],0.003412