In [1]:
import pandas as pd
import numpy as np
# import seaborn as sns

In [2]:
f = '/home/qlyu/mydata/data/v1_astro/t2/spout/tf_to_gene_adj.tsv'
df_raw = pd.read_csv(f, sep='\t')
df = df_raw[df_raw['TF']=='Rfx4']
df

           TF         target    importance  regulation       rho
878714   Rfx4         Pde10a  1.561515e+00          -1 -0.278113
878715   Rfx4            Itk  9.361071e-07           0 -0.005190
878716   Rfx4          Dnhd1  1.381462e-01           0 -0.020287
878717   Rfx4           Ficd  7.433483e-02           0  0.024870
878718   Rfx4         Hspbp1  2.165060e-01          -1 -0.044868
...       ...            ...           ...         ...       ...
889027   Rfx4        Gm13270  4.140023e-01           0  0.021422
889028   Rfx4          Zbtb6  9.337742e-01           1  0.030133
889029   Rfx4           Dhx8  2.826261e-09           0  0.003470
889030   Rfx4  C130074G19Rik  2.544271e-06           0 -0.027333
1247100  Rfx4           Rfx4  1.803023e+01           1  1.000000

[10318 rows x 5 columns]

In [3]:
df['regulation'].value_counts()

-1    4070
 1    3147
 0    3101
Name: regulation, dtype: int64

In [4]:
df['rhoa'] = np.abs(df['rho'])
df['importance_rank_pct'] = df['importance'].rank(pct=True, ascending=False)
df['importance_rank'] = df['importance'].rank(ascending=False)
df.groupby('regulation').mean()

/tmp/ipykernel_3289918/2507916231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rhoa'] = np.abs(df['rho'])
/tmp/ipykernel_3289918/2507916231.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['importance_rank_pct'] = df['importance'].rank(pct=True, ascending=False)
/tmp/ipykernel_3289918/2507916231.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['importance_rank'] = df['importance'].rank(ascending=False)
/tmp/ipykernel_3289918/2507916231.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('regulation').mean()

,importance,rho,rhoa,importance_rank_pct,importance_rank
regulation,,,,,
-1,1.276684,-0.117793,0.117793,0.419939,4332.930467
0,0.276109,-0.000536,0.013963,0.719517,7423.973557
1,1.346533,0.137852,0.137852,0.387393,3997.124881

In [5]:
assert 'Mertk' in df['target'].unique()
df[df['target']=='Mertk']

,TF,target,importance,regulation,rho,rhoa,importance_rank_pct,importance_rank
884805,Rfx4,Mertk,14.089804,1,0.665074,0.665074,0.002229,23.0

In [6]:
df.sort_values('importance_rank')

,TF,target,importance,regulation,rho,rhoa,importance_rank_pct,importance_rank
1247100,Rfx4,Rfx4,1.803023e+01,1,1.000000,1.000000,0.000097,1.0
886825,Rfx4,Zbtb20,1.803022e+01,1,0.660149,0.660149,0.000194,2.0
887069,Rfx4,Slc1a3,1.786011e+01,1,0.678768,0.678768,0.000291,3.0
887045,Rfx4,Atp1a2,1.712544e+01,1,0.650286,0.650286,0.000388,4.0
886547,Rfx4,Npas3,1.567794e+01,1,0.663597,0.663597,0.000485,5.0
...,...,...,...,...,...,...,...,...
881221,Rfx4,Gm34838,5.467769e-11,0,-0.008754,0.008754,0.999612,10314.0
881051,Rfx4,Rhoh,5.220456e-11,0,0.009792,0.009792,0.999709,10315.0
887989,Rfx4,Atp4a,2.739665e-11,0,0.007742,0.007742,0.999806,10316.0
887353,Rfx4,Prx,2.140658e-11,0,-0.009921,0.009921,0.999903,10317.0
886810,Rfx4,9230109A22Rik,1.124011e-16,0,-0.017563,0.017563,1.000000,10318.0

In [7]:
dft = df_raw[df_raw['target']=='Mertk']
dft

                    TF target  importance  regulation       rho
280      2610021A01Rik  Mertk    0.005659          -1 -0.064526
6034            Acaa1a  Mertk    0.002212           0  0.026018
8466                Ar  Mertk    0.146472          -1 -0.178102
14842             Arnt  Mertk    0.002125           0 -0.026252
19024            Arnt2  Mertk    0.002255           0  0.008413
...                ...    ...         ...         ...       ...
1216725         Zfp704  Mertk    0.905725          -1 -0.280004
1221718         Zfp711  Mertk    0.019627          -1 -0.163171
1225886         Zfp777  Mertk    0.000014          -1 -0.038747
1229564         Zfp786  Mertk    0.008112           0 -0.027260
1237030            Zfx  Mertk    0.000072           0 -0.000723

[145 rows x 5 columns]

In [9]:
dft['regulation'].value_counts()

 1    66
-1    48
 0    31
Name: regulation, dtype: int64

In [12]:
dft.sort_values('importance', ascending=False).head(20)

             TF target  importance  regulation       rho
986691     Sox6  Mertk   28.050766           1  0.770120
633077     Nfia  Mertk   16.657469           1  0.634558
196186     Dbx2  Mertk   16.340686           1  0.617155
541597    Mef2c  Mertk   15.656412          -1 -0.721814
884805     Rfx4  Mertk   14.089804           1  0.665074
317209    Foxo1  Mertk   10.768593           1  0.595131
914960    Satb2  Mertk    9.402799          -1 -0.530645
845841      Rb1  Mertk    6.598563           1  0.349341
829315    Prrx1  Mertk    5.660029           1  0.538569
91946    Bcl11a  Mertk    4.360195          -1 -0.493170
356897     Hes5  Mertk    4.247287           1  0.490625
797371   Pou2f1  Mertk    2.554316           1  0.321494
1001435    Sox9  Mertk    1.843258           1  0.460142
1031716  Srebf1  Mertk    1.310764           1  0.365652
283210     Etv4  Mertk    1.250713           1  0.413425
554981    Meis1  Mertk    1.235633           1  0.409066
180282     Cux2  Mertk    1.000662          -1 -0.333974
262946     Emx2  Mertk    0.987197           1  0.390579
240549     Elf1  Mertk    0.972211           1  0.359018
749887     Pax6  Mertk    0.952158           1  0.406236

# region to gene

In [18]:
f = '/home/qlyu/mydata/data/v1_astro/t2/spout/region_to_gene_adj.tsv'
df2_raw = pd.read_csv(f, sep='\t')
df2_raw['importance_x_abs_rho_rank'] = df2_raw['importance_x_abs_rho'].rank(pct=True, ascending=False) 
print(df2_raw.shape)
df2 = df2_raw[df2_raw['target']=='Mertk'].sort_values('importance_x_abs_rho', ascending=False)
print(df2.shape)
df2
# df

(680504, 8)
(47, 8)

,target,region,importance,rho,importance_x_rho,importance_x_abs_rho,Distance,importance_x_abs_rho_rank
338178,Mertk,chr2:128709104-128709605,1.184319e-01,0.746525,8.841242e-02,8.841242e-02,[-64540],0.000075
338146,Mertk,chr2:128497800-128498301,9.424160e-02,-0.896956,-8.453054e-02,8.453054e-02,[42826],0.000084
338179,Mertk,chr2:128704410-128704911,8.572007e-02,0.800078,6.858272e-02,6.858272e-02,[-59846],0.000199
338180,Mertk,chr2:128698559-128699060,1.129459e-01,0.573247,6.474588e-02,6.474588e-02,[-53996],0.000254
338173,Mertk,chr2:128745803-128746304,9.929474e-02,0.602391,5.981430e-02,5.981430e-02,[-101240],0.000350
338181,Mertk,chr2:128698013-128698514,7.017670e-02,0.768135,5.390518e-02,5.390518e-02,[-53450],0.000534
338168,Mertk,chr2:128786705-128787206,5.544115e-02,0.887918,4.922718e-02,4.922718e-02,[-142142],0.000762
338182,Mertk,chr2:128687421-128687922,6.059751e-02,-0.564160,-3.418668e-02,3.418668e-02,[-42858],0.002649
338174,Mertk,chr2:128738704-128739205,5.963683e-02,0.566037,3.375664e-02,3.375664e-02,[-94140],0.002768
338184,Mertk,chr2:128686977-128687478,4.524357e-02,0.738566,3.341536e-02,3.341536e-02,[-42414],0.002860
338169,Mertk,chr2:128758624-128759125,3.581964e-02,0.879016,3.148603e-02,3.148603e-02,[-114060],0.003412
338159,Mertk,chr2:128444598-128445099,2.597790e-02,0.849919,2.207912e-02,2.207912e-02,[96028],0.007772
338175,Mertk,chr2:128717686-128718187,2.444875e-02,0.856874,2.094949e-02,2.094949e-02,[-73122],0.008675
338148,Mertk,chr2:128566706-128567207,1.430078e-02,0.892188,1.275898e-02,1.275898e-02,[0],0.021099
338190,Mertk,chr2:128395820-128396321,1.654359e-02,0.764221,1.264296e-02,1.264296e-02,[144806],0.021402
338155,Mertk,chr2:128465130-128465631,1.371785e-02,-0.781564,-1.072138e-02,1.072138e-02,[75496],0.027571
338162,Mertk,chr2:128414519-128415020,1.149126e-02,-0.880915,-1.012283e-02,1.012283e-02,[126106],0.029876
338177,Mertk,chr2:128713420-128713921,1.351887e-02,0.569186,7.694756e-03,7.694756e-03,[-68856],0.042846
338149,Mertk,chr2:128498481-128498982,9.936025e-03,-0.448883,-4.460116e-03,4.460116e-03,[42144],0.079525
338152,Mertk,chr2:128498215-128498716,9.072077e-03,-0.472458,-4.286173e-03,4.286173e-03,[42410],0.082793
338145,Mertk,chr2:128468965-128469466,7.774823e-03,-0.546258,-4.247059e-03,4.247059e-03,[71660],0.083563
338187,Mertk,chr2:128412012-128412513,4.280716e-03,-0.495342,-2.120420e-03,2.120420e-03,[128614],0.160045
338166,Mertk,chr2:128678605-128679106,3.525711e-03,0.426438,1.503496e-03,1.503496e-03,[-34042],0.210917
338154,Mertk,chr2:128458041-128458542,2.726128e-03,-0.228362,-6.225446e-04,6.225446e-04,[82584],0.367145
338151,Mertk,chr2:128572782-128573283,1.787902e-03,-0.321811,-5.753666e-04,5.753666e-04,[0],0.382158
338171,Mertk,chr2:128746788-128747289,7.487170e-04,0.296976,2.223509e-04,2.223509e-04,[-102224],0.551755
338183,Mertk,chr2:128687163-128687664,3.322620e-04,-0.338391,-1.124346e-04,1.124346e-04,[-42600],0.654718
338167,Mertk,chr2:128674526-128675027,3.386606e-04,0.264365,8.952999e-05,8.952999e-05,[-29962],0.684836
338165,Mertk,chr2:128603050-128603551,2.529010e-04,0.171162,4.328699e-05,4.328699e-05,[0],0.766138
338170,Mertk,chr2:128758293-128758794,1.737546e-04,0.187761,3.262432e-05,3.262432e-05,[-113730],0.792279
338186,Mertk,chr2:128678829-128679330,1.409795e-04,-0.174713,-2.463098e-05,2.463098e-05,[-34266],0.815521
338161,Mertk,chr2:128429092-128429593,3.070721e-04,0.065625,2.015159e-05,2.015159e-05,[111534],0.830701
338185,Mertk,chr2:128686736-128687237,8.281312e-05,0.151475,1.254415e-05,1.254415e-05,[-42172],0.861755
338189,Mertk,chr2:128662064-128662565,2.077763e-04,0.056710,1.178292e-05,1.178292e-05,[-17500],0.865466
338160,Mertk,chr2:128432681-128433182,6.211399e-05,-0.181386,-1.126663e-05,1.126663e-05,[107944],0.868013
338157,Mertk,chr2:128457761-128458262,6.301598e-05,0.078882,4.970806e-06,4.970806e-06,[82864],0.906720
338176,Mertk,chr2:128717408-128717909,1.323604e-04,-0.021936,-2.903401e-06,2.903401e-06,[-72844],0.925133
338163,Mertk,chr2:128412306-128412807,4.990710e-05,0.034963,1.744910e-06,1.744910e-06,[128320],0.938580
338150,Mertk,chr2:128467391-128467892,3.891887e-05,-0.042971,-1.672370e-06,1.672370e-06,[73234],0.939554
338147,Mertk,chr2:128497940-128498441,2.120373e-04,0.007118,1.509236e-06,1.509236e-06,[42686],0.941864
338156,Mertk,chr2:128573122-128573623,1.036775e-04,-0.010986,-1.138966e-06,1.138966e-06,[0],0.947699
338172,Mertk,chr2:128746221-128746722,2.707757e-05,0.040824,1.105404e-06,1.105404e-06,[-101658],0.948275
338191,Mertk,chr2:128537335-128537836,3.128003e-05,0.017860,5.586666e-07,5.586666e-07,[3290],0.959093
338164,Mertk,chr2:128465517-128466018,3.784246e-05,0.014078,5.327630e-07,5.327630e-07,[75108],0.959732
338153,Mertk,chr2:128467013-128467514,7.894096e-07,-0.023889,-1.885838e-08,1.885838e-08,[73612],0.981955
338158,Mertk,chr2:128457059-128457560,3.992519e-06,-0.003892,-1.553748e-08,1.553748e-08,[83566],0.982468
338188,Mertk,chr2:128676094-128676595,1.696258e-08,-0.014572,-2.471747e-10,2.471747e-10,[-31530],0.987977